use onlinecourse;

CREATE TABLE register_order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    learner_id INT NOT NULL,
	FOREIGN KEY (learner_id) REFERENCES  user(id) ON DELETE RESTRICT
);